### ISSUE TITLE
bitbake fsl-image-base：error

### ISSUE THREAD

**Issue by flyalltheway** [nxp-auto-linux/auto_yocto_bsp#1]
PowerEdge-R740:~/fsl-auto-yocto-bsp/build_s32r45evb$ bitbake fsl-image-base
Traceback (most recent call last):
  File "/home/.../fsl-auto-yocto-bsp/sources/poky/bitbake/bin/bitbake", line 19, in <module>
    import bb
  File "/home/.../fsl-auto-yocto-bsp/sources/poky/bitbake/lib/bb/__init__.py", line 119, in <module>
    from bb import fetch2 as fetch
  File "/home/.../fsl-auto-yocto-bsp/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 26, in <module>
    import bb.persist_data, bb.utils
  File "/home/.../fsl-auto-yocto-bsp/sources/poky/bitbake/lib/bb/persist_data.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by flyalltheway** [comment]
Python 3.10 have some compatibility issues, I replace Python 3.6.9 is ok
